### ISSUE TITLE
interoperability with other macaroons implementations

### ISSUE THREAD

**Issue by sevenEng** [nojb/ocaml-macaroons#5]
Actually we came across this problem when trying to verify some macaroons produced by macaroons.js. Related issue: https://github.com/me-box/databox-arbiter/issues/27

After experimenting and referring to some other implementations with @yousefamar, here are three points that may need to be fixed:
1. packet header encoding/decoding: [libmacaroons' implementation](https://github.com/rescrv/libmacaroons/blob/6d125f7c23ba2a3f8d91e302e1e6a119a055cfa0/packet.c#L51) assumes a max value of 65535(uint16) and hexify it as the four byte header
2. alphabet used by base64 codec: it seems that [an uri-safe alphabet](https://github.com/rescrv/libmacaroons/blob/6d125f7c23ba2a3f8d91e302e1e6a119a055cfa0/base64.c#L58) should be used
3. the primitives of hmac algorigthm used to produce the signature: ocaml-sodium's auth function uses primitive [hmacsha512256](https://github.com/dsheets/ocaml-sodium/blob/master/lib_gen/sodium_bindgen.ml#L22), which on the c part will call [hmacsha512](https://github.com/jedisct1/libsodium/blob/master/src/libsodium/crypto_auth/hmacsha512256/auth_hmacsha512256.c#L47) eventually. But both implementation of c [libmacaroons](https://github.com/rescrv/libmacaroons/blob/6d125f7c23ba2a3f8d91e302e1e6a119a055cfa0/port.c#L103) and python [pymacaroons](https://github.com/ecordell/pymacaroons/blob/master/pymacaroons/utils.py#L51) use sha256 explicitly.

This lib is a nice implementation itself, clear interfaces and realy handy to use. But it would be better if it could inter-operate with other macaroon libs.

I'll submit a PR dealling with the first two points. But not sure about the third one, it seems there is no way to demand usage of sha256 for auth functions at the moment @dsheets. For now, I can work around this by making a local pin to use sha256 primitives.

**Comment by nojb** [comment]
Hi @sevenEng, thanks a lot for your contribution.  I am not working actively on this project but will gladly and happily merge any good contribution and will do my best to make any further improvements possible.

**Comment by dsheets** [comment]
There is no explicit sha256 binding at the moment. libsodium calls `hmacsha512256` `crypto_auth` so that is what we use for the `Auth` module. I would welcome a PR for an `Auth_hmacsha256` module (and `Auth_hmacsha512` and `Auth_hmacsha512256` modules) which should be just different invocations of the same `Gen_auth` functor plus some interface and documentation.

**Comment by sevenEng** [comment]
Thanks for your quick response! :+1:
I'll close this up for now and see what I can do about the libsodium bindings later.
Thanks! :smiley:
